# Generated by Django 3.2.19 on 2026-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20260816_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_certification',
            field=models.CharField(blank=True, default='', help_text='Example: U, UA, A', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
