# Generated by Django 3.2.19 on 2026-08-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20260818_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Movie length in minutes', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default='', help_text='Paste a YouTube video link'),
        ),
    ]
