# Generated by Django 3.2.19 on 2026-08-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20260819_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_certification',
            field=models.CharField(blank=True, choices=[('U', 'U - Universal'), ('UA', 'UA - Parental Guidance'), ('A', 'A - Adults Only'), ('S', 'S - Restricted to Special Class')], default='', max_length=2),
        ),
    ]
