# Generated by Django 3.2.19 on 2026-08-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20260822_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
